### PR TITLE
feat: support local model path

### LINKED ISSUE #128: How to use local path to deploy model?
### Prerequisites

- [X] I have read the [ServerlessLLM documentation](https://serverlessllm.github.io/).
- [X] I have searched the [Issue Tracker](https://github.com/ServerlessLLM/ServerlessLLM/issues) to ensure this hasn't been reported before.

### System Information

- ServerlessLLM 0.5.0 
- Linux with 2 GPUs

### Problem Description

In quick start guide(https://serverlessllm.github.io/docs/stable/getting_started/quickstart), the deploy command is "sllm-cli deploy --model facebook/opt-1.3b".
I can not connect to HuggingFace for now, but I have the model in my local disk, how can I use the local path to deploy model?

### Steps to Reproduce

Code snippets:
```python

```

Steps to reproduce:
1.
2.
3.

### Expected Behavior

_No response_

### Additional Context

_No response_

### Usage Statistics (Optional)

_No response_

### PR DESCRIPTION
**Pull request by dblate**
## Description
Supports configuration of the local model path to omit downloading.

## Motivation
close #128.
Sometimes there is already a local model, or a network problem connecting to HuggingFace, so we want to use local model instead. 
Now we can achieve this by configuring `backend_config.pretrained_model_name_or_path`, it both supports transformers and vllm backends, for example:

```json
{
    "model": "facebook/opt-1.3b",
    "backend": "transformers",
    "num_gpus": 1,
    "auto_scaling_config": {
        "metric": "concurrency",
        "target": 1,
        "min_instances": 0,
        "max_instances": 10
    },
    "backend_config": {
        "pretrained_model_name_or_path": "/root/users/dblate/facebook/opt-1.3b",
        "device_map": "auto",
        "torch_dtype": "float16"
    }
}
```

Since the pull request contains many file changes, I'd like to state my points:
- In config, `model` and `pretrained_model_name_or_path` should be two independent fields
    - `model` used to be an identifier, like as internal keys for routers or serverless format file path
    - `pretrained_model_name_or_path` used to get the model, it can be a HuggingFace model name, or local path
- They can be the same sometimes, but not always

Feel free to modify my code or reject it if necessary. 

## Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update

## Checklist
- [x] I have read the [CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) guide.
- [ ] I have updated the tests (if applicable).
- [ ] I have updated the documentation (if applicable).

### CODE REVIEW

**Review by SiyangShao — APPROVED** [review]
LGTM. I've tested this PR with `opt-1.3b` on both vLLM backend and transformer backend, and both of them works fine. It would be better if you could mention how to use it (i.e., fill your local path into `pretrained_model_name_or_path` ) in the docs (maybe directly under https://github.com/ServerlessLLM/ServerlessLLM/blob/main/docs/stable/cli/cli_api.md#example-configuration-file-configjson).

**Review by SecretSettler — APPROVED** [review]
This looks good for me. Could you please also update the doc or add an example inside the example folder for guidance.

**Comment by dblate** [comment]
I will update doc and example later.

**Comment by SecretSettler** [comment]
Hi,
We noticed that you closed the PR. Could you share your concerns with us?

**Comment by SecretSettler** [comment]
Reopen

**Comment by dblate** [comment]
This must be a misoperation... I am dealing with a code conflict.

**Comment by SecretSettler** [comment]
Okay, could you please request another PR so that we can review and merge?

**Comment by dblate** [comment]
I have requested a new PR: https://github.com/ServerlessLLM/ServerlessLLM/pull/177, please review at your convenience.

**Pull request closed without merging**
