### PR TITLE
[Docs] Minor fix doc

### PR DESCRIPTION
**Pull request by JustinTong0323**
This pr:
1. rename SLLM-CLI Documentation.md to sllm_cli_doc.md
2. fix inconsistent example

related to issue #40.

### CODE REVIEW

**Comment by future-xy** [comment]
Could you fix the second advice of #40 too? I think they mean quickstart guide and docker quickstart guide.

**Comment by JustinTong0323** [comment]
3. in quickstart guide, clarify when the user should open new terminals.

**Comment by future-xy** [comment]
> 3. in quickstart guide, clarify when the user should open new terminals.

I think #40 is asking **where** to start a new terminal.

**Comment by JustinTong0323** [comment]
> > 3. in quickstart guide, clarify when the user should open new terminals.
> 
> I think #40 is asking **where** to start a new terminal.

But in quickstart guide we only work on one machine, so what is the meaning of **where**?

**Comment by future-xy** [comment]
> > > 3. in quickstart guide, clarify when the user should open new terminals.
> > 
> > 
> > I think #40 is asking **where** to start a new terminal.
> 
> But in quickstart guide we only work on one machine, so what is the meaning of **where**?

Please reply in the issue for clarification.

**Review by future-xy — APPROVED** [review]

**Pull request merged**
