### PR TITLE
feat: ROCm support

### PR DESCRIPTION
**Pull request by SiyangShao**
## Description
This PR modifies the build of sllm-store in order to support HIP/ROCm. It is the latest version of the closed PR https://github.com/ServerlessLLM/ServerlessLLM/pull/33

## Motivation
Support ROCm platfrom

## Type of Change
- [x] New feature
- [x] Documentation update

## Checklist
- [x] I have read the [CONTRIBUTION](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/CONTRIBUTING.md) guide.
- [x] I have updated the tests (if applicable).
- [x] I have updated the documentation (if applicable).

### CODE REVIEW

**Comment by SiyangShao** [comment]
TODO:
+ [ ] Add document about ROCm
+ [ ] Add tests for ROCm platfrom

**Comment by SiyangShao** [comment]
Python tests for CUDA platform also works for ROCm platform, there's no need to change.

**Comment by SiyangShao** [comment]
C++ tests after modification can also be runned:
```
(sllm_dev) shaosy@hacc-gpu7:/mnt/home/shaosy/ServerlessLLM/sllm_store/build$ ctest --output-on-failure
Test project /mnt/home/shaosy/ServerlessLLM/sllm_store/build
    Start 1: runTests
1/1 Test #1: runTests .........................   Passed    7.12 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   7.12 sec
```

**Review by luomai — APPROVED** [review]
LGTM. Let's mark the AMD support as experimental for now. 

By the way, it is good to briefly discuss what are our next steps for supporting AMD beyond the experimental and when it could become stable.

**Review by future-xy — APPROVED** [review]

**Pull request merged**
